spring:
  datasource:
    url: jdbc:postgresql://52.77.101.54:5432/ecommerce_db
    username: px4
    password: px4K3@2003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.time_zone: Asia/Ho_Chi_Minh
  session:
    store-type: none
  jackson:
    time-zone: Asia/Ho_Chi_Minh